name: couple_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  dio: 5.3.2
  get: 4.6.6
  intl: 0.18.0
  shared_preferences: 2.2.1
  lottie: 1.3.0
  basic_utils: 5.6.1
  jiffy: 6.2.1
  loader_overlay: 2.1.0
  collection: 1.18.0
  package_info_plus: 4.1.0
  shimmer: 2.0.0
  device_info: 2.0.3
  realm: 1.6.0
  workmanager: 0.5.2
  permission_handler: 11.1.0
  url_launcher: 6.2.1
  flutter_multi_formatter: ^2.12.8
  path_provider: ^2.1.3
  file_picker: ^8.0.0+1
  firebase_storage: ^11.7.7
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.19.5
  flutter_local_notifications: ^17.1.2
  firebase_core: ^2.32.0
  equatable: ^2.0.5
  geolocator: ^12.0.0
  google_maps_flutter: ^2.9.0
  image_picker: ^1.1.2
  device_info_plus: ^10.1.2
  connectivity_plus: ^6.0.5
  battery_plus: ^6.0.2
  firebase_messaging: ^14.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/font/
    - assets/images/
    - assets/images/maps.png
    - assets/images/default_profile.png
    - assets/lottie/
  fonts:
    - family: Barlow
      fonts:
        - asset: assets/font/Barlow-Black.ttf
        - asset: assets/font/Barlow-BlackItalic.ttf
        - asset: assets/font/Barlow-Bold.ttf
        - asset: assets/font/Barlow-BoldItalic.ttf
        - asset: assets/font/Barlow-ExtraBold.ttf
        - asset: assets/font/Barlow-ExtraBoldItalic.ttf
        - asset: assets/font/Barlow-ExtraLight.ttf
        - asset: assets/font/Barlow-ExtraLightItalic.ttf
        - asset: assets/font/Barlow-Italic.ttf
        - asset: assets/font/Barlow-Light.ttf
        - asset: assets/font/Barlow-LightItalic.ttf
        - asset: assets/font/Barlow-Medium.ttf
        - asset: assets/font/Barlow-MediumItalic.ttf
        - asset: assets/font/Barlow-Regular.ttf
        - asset: assets/font/Barlow-SemiBold.ttf
        - asset: assets/font/Barlow-SemiBoldItalic.ttf
        - asset: assets/font/Barlow-Thin.ttf
        - asset: assets/font/Barlow-ThinItalic.ttf
