// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return android;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4etiLbMgTbsjCKk4xy3eGPzwT2dRH6M4',
    appId: '1:53973977460:android:1140c76758566a93af8421',
    messagingSenderId: '53973977460',
    projectId: 'couple-3c18d',
    authDomain: 'couple-3c18d.firebaseapp.com',
    storageBucket: 'gs://couple-3c18d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4etiLbMgTbsjCKk4xy3eGPzwT2dRH6M4',
    appId: '1:53973977460:android:1140c76758566a93af8421',
    messagingSenderId: '53973977460',
    projectId: 'couple-3c18d',
    authDomain: 'couple-3c18d.firebaseapp.com',
    storageBucket: 'gs://couple-3c18d.appspot.com',
    iosClientId: '',
    iosBundleId: '',
  );
}
